language: php
php:
  - 5.4
  - 5.5
  - 5.6
before_script:
  - ./bin/initialize-dependencies.sh
  - ./bin/initialize-ci.sh 1.7.7
  - php ./test/Integration/fixtures/load.php
script: bin/phpunit --group __nogroup__,integration
notifications:
  email:
    - alessandro.nadalin@gmail.com
    - ing.davidino@gmail.com
    - suppakilla@gmail.com
    - weinmaster@gmail.com
